ROM_KEY_SCAN	EQU $028E
ROM_KEY_REPEAT	EQU $031C
ROM_BEEPER		EQU $03B5
ROM_BYTES_SAVE	EQU $04C6
ROM_BYTES_LOAD	EQU $0562

PORT_BORDER		EQU $FE
STACK_LOADER	EQU $FF00

FACE_NORTH		EQU 0
FACE_EAST		EQU 1
FACE_SOUTH		EQU 2
FACE_WEST		EQU 3

; ------------------------
; screen 4000 - 5AFF
SCR_ATTR		EQU $5800
SCR_ATTR_LEN	EQU $0300
; ------------------------

; RAM work buffers (fixed addresses; overlay shipped data at load time)
LOAD_HEADER_BUF	EQU $FF44	; loader: 7-byte tape header destination
LOAD_FILENAME	EQU $FF5A	; loader: filename to match against headers
VIEW_MAP_BUFFER	EQU $FFE2	; 3D-view cell-map buffer (sample_view_cell)

CODE_CR			EQU $0D
CODE_ABORT		EQU $1B		; ext mode
CODE_C8			EQU $C8
CODE_C9			EQU $C9

ICON_LIGHT		EQU 1
ICON_CARPET		EQU 2
ICON_EYE		EQU 3
ICON_SHIELD		EQU 4
ICON_ARROW_UP	EQU 5
ICON_ARROW_RI	EQU 6
ICON_ARROW_DN	EQU 7
ICON_ARROW_LE	EQU 8
ICON_SPACE		EQU 9

; -----------------------------
;	SHOW_NAME_PIC_AB
;	SHOW_NAME_AND_PICTURE
;	SHOW_PIC_BY_A
; -----------------------------
PIC_ROSCOES			EQU $02
PIC_ZOMBIE			EQU $03
PIC_GUILD			EQU $0D
PIC_SHOPPE			EQU $0E
PIC_TAVERN			EQU $0F
PIC_TEMPLE			EQU $11
PIC_BUILDING		EQU $12
PIC_REVIEWBOARD		EQU $13
PIC_GRAVE			EQU $19
PIC_GUARDIAN		EQU $1A
PIC_TOWER			EQU $1B

; -----------------------------
; IY variables at $5FAB		
; GET_GAME_VARIABLE
; GAME_VARIABLES + VAR_
; -----------------------------
VAR_PARTY_SIZE		EQU $00
VAR_DAY_OUTER_CTR	EQU $04
VAR_DISPLAY_STATE	EQU $06
VAR_DUNGEON_LEVEL	EQU $07
VAR_DAY_MID_CTR		EQU $08
VAR_SPELL_STATE		EQU $0B
VAR_DAY_INNER_CTR	EQU $0C
VAR_COMBAT_MODE		EQU $0E
VAR_EVENT_DEPTH		EQU $0F
VAR_SPELL_ACTIVE	EQU $10
VAR_SPELL_ID		EQU $11
VAR_TURN_PROCESSING	EQU $12
VAR_REDRAW_STATS	EQU $13
VAR_HERO_SLOT		EQU $14
VAR_SPELL_DURATION	EQU $15
VAR_BARD_SONG_LVL	EQU $1D
VAR_CAST_HERO		EQU $26
VAR_DAY_TIMER_CHK	EQU $29
VAR_ANIM_SPEED_FLAG	EQU $2E
VAR_NIGHT_TIMER		EQU $2F
VAR_WEAPON_BONUS	EQU $34
VAR_DUNGEON_STEPS	EQU $35
VAR_TREASURE_FLAG	EQU $36
VAR_TEMPLE_TIMER	EQU $37
VAR_VIEW_Y_OFFSET	EQU $38
VAR_VIEW_X_OFFSET	EQU $39
VAR_TELEPORT_MODE	EQU $3B
VAR_SAVE_STATE_HI	EQU $3E
VAR_SAVE_STATE_LO	EQU $3D
VAR_AREA_MODE		EQU $3F
VAR_REVEAL_FLAG		EQU $40
VAR_TEXT_BUF_PTR	EQU $41
VAR_TREASURE_HI		EQU $43
VAR_TREASURE_LO		EQU $45
VAR_PORTRAIT_CTR	EQU $48
VAR_CURRENT_SPELL	EQU $4B
VAR_CURRENT_ACTOR	EQU $4C
VAR_ENEMY_COUNT		EQU $4D
VAR_ACTIVE_ENEMY	EQU $4E
VAR_DISPLAY_COUNT	EQU $4F
VAR_DAMAGE_TYPE		EQU $50
VAR_FLEE_SUCCESS	EQU $51
VAR_TARGET_ID		EQU $53
VAR_ICON_CODE		EQU $55
VAR_SONG_MODIFIER	EQU $56
VAR_SONG_EFFECT		EQU $57
VAR_COMBAT_SPEED	EQU $58
VAR_SPEED_LOOKUP	EQU $59
VAR_AMBUSH_FLAG		EQU $5A
VAR_ENCOUNTER_CTR	EQU $5B
VAR_BREATH_COUNT	EQU $5C
VAR_BASE_DAMAGE		EQU $5F
VAR_DEFENSE_BONUS	EQU $60
VAR_INITIATIVE_FLAG	EQU $61
VAR_AC_MOD_ENEMY	EQU $62
VAR_STAT_MODIFIER	EQU $63
VAR_DAMAGE_PENALTY	EQU $64
VAR_BREATH_VALUE	EQU $65
VAR_ALLY_COUNTER	EQU $66
VAR_ROUND_NUMBER	EQU $67
VAR_ANTIMAGIC		EQU $68
VAR_ENEMY_SLOT		EQU $6B
VAR_XP_THRESHOLD	EQU $6C
VAR_ATTACK_MODIFIER	EQU $6D
VAR_MEMBER_NUM		EQU $6E
VAR_PLURAL_FLAG		EQU $6F
VAR_TARGET_SELECT	EQU $70
VAR_PRINT_POS		EQU $72
VAR_GOLD_FOUND_HI	EQU $74
VAR_XP_TOTAL_HI		EQU $76

VAR_COORD_SO_NO		EQU $01	; north-south  (+north -south)
VAR_COORD_WE_EA		EQU $02	; west/east (+east -west)
VAR_FACE_DIRECTION	EQU $03
VAR_DAY_OUTER		EQU $05
VAR_DAY_INNER		EQU $0D
VAR_DAY_PART		EQU $1E
VAR_LIGHT			EQU $1F
VAR_CARPET			EQU $20
VAR_COMPASS_ON		EQU $21
VAR_EYE				EQU $22
VAR_SHIELD			EQU $23
VAR_KEEP_PRESSED	EQU $24
VAR_PRESSED_KEY		EQU $25
VAR_LIGHT_DIST		EQU $27
VAR_REVEAL_SECRET	EQU $28
VAR_PAUSE			EQU $30	; 0=running 1=paused
VAR_RND_HI			EQU $32
VAR_RND_LO			EQU $33
VAR_UNDERGROUND		EQU $3A
VAR_INFO_ROW_POS	EQU $46
VAR_INFO_COL_POS	EQU $47
VAR_SPELL_CLASS		EQU $49
VAR_SPELL_LEVEL		EQU $4A
VAR_ACTIVE_HERO		EQU $52
VAR_COPY_DAYPART	EQU $54
VAR_CURSOR_ROW		EQU $5D	; (0-23)
VAR_CURSOR_COL		EQU $5E
VAR_CURRENT_PARAM	EQU $69

; -----------------------------
; IX variables
; GET_ATTR_BY_PARAM
; GET_ATTR_BY_PARAM_SAVE_HL
; -----------------------------
CHAR_SPEED			EQU $12
CHAR_SAVED_STATS	EQU $13
CHAR_ATTACK_SPEC	EQU $15
CHAR_DEFENSE_SPEC	EQU $16
CHAR_SPECIAL_FLAG	EQU $17
CHAR_BACKUP_PARAMS	EQU $60
CHAR_SWAP_STATS		EQU $63

CHAR_NAME			EQU $00
CHAR_NAME_TERM		EQU $0F
CHAR_PARAMS_HI		EQU $10
CHAR_PARAMS_LO		EQU $11
CHAR_EXP_START		EQU $14
CHAR_EXP_END		EQU $1F	; end of 12 bytes block
CHAR_MAXLEVEL_HI	EQU $20
CHAR_MAXLEVEL_LO	EQU $21
CHAR_LEVEL_HI		EQU $22
CHAR_LEVEL_LO		EQU $23
CHAR_GOLD_START		EQU $24
CHAR_GOLD_END		EQU $2F	; end of 12 bytes block
CHAR_HITS_HI		EQU $30
CHAR_HITS_LO		EQU $31
CHAR_COND_HI		EQU $32
CHAR_COND_LO		EQU $33
CHAR_SPPT_MAX_HI	EQU $34	; spell points
CHAR_SPPT_MAX_LO	EQU $35
CHAR_SPPT_HI		EQU $36
CHAR_SPPT_LO		EQU $37
CHAR_CLASS			EQU $38
CHAR_RACE			EQU $39
CHAR_WON_COMBATS_HI	EQU $3C
CHAR_WON_COMBATS_LO	EQU $3D
CHAR_STATUS			EQU $3E
CHAR_NATURAL_AC		EQU $3F
CHAR_SORC_LEVEL		EQU $40
CHAR_CONJ_LEVEL		EQU $41
CHAR_MAGI_LEVEL		EQU $42
CHAR_ROGUE_DISARM	EQU $44
CHAR_ROGUE_DETECT	EQU $45
CHAR_ROGUE_HIDE		EQU $46
CHAR_HUNTER_CHANCE	EQU $48
CHAR_BARD_SONGS		EQU $49
CHAR_NEG_FLAG		EQU $4D
CHAR_FORMER_HEALTH	EQU $4E
CHAR_ATT_ROUND		EQU $4F
CHAR_INVENTORY		EQU $50
CHAR_ITEM_1_ID		EQU $51
CHAR_LASTITEM_STATE	EQU $5E
CHAR_LASTITEM_ID	EQU $5F
CHAR_POS_IN_PARTY	EQU $64

; -----------------------------
; enemy
; -----------------------------
ENEMY_ALIVE			EQU $00
ENEMY_ACTIVE_FLAG	EQU $10
ENEMY_COMBAT_DATA	EQU $11
ENEMY_SPEED			EQU $15
ENEMY_ATTACK_SPEC	EQU $16
ENEMY_SPECIAL_FLAG	EQU $17
ENEMY_HITS			EQU $31
ENEMY_COND			EQU $33
ENEMY_CLASS			EQU $38

; -----------------------------
; classes
; -----------------------------
CLASS_WARRIOR		EQU $00
CLASS_SORCERER		EQU $01
CLASS_WIZARD		EQU $02
CLASS_CONJURER		EQU $03
CLASS_MAGICIAN		EQU $04
CLASS_ROGUE			EQU $05
CLASS_BARD			EQU $06
CLASS_PALADIN		EQU $07
CLASS_HUNTER		EQU $08
CLASS_MONK			EQU $09
CLASS_PARTY			EQU $0A

; -----------------------------
; races
; -----------------------------
RACE_HUMAN			EQU $00
RACE_ELF			EQU $01
RACE_DWARF			EQU $02
RACE_HOBBIT			EQU $03
RACE_HALFELF		EQU $04
RACE_HALFORC		EQU $05
RACE_GNOME			EQU $06

; -----------------------------
; statuses
; -----------------------------
STATUS_OK			EQU $00
STATUS_POISONED		EQU $01
STATUS_OLD			EQU $02
STATUS_DEAD			EQU $03
STATUS_STONED		EQU $04
STATUS_PARALYZED	EQU $05
STATUS_POSSESSED	EQU $06
STATUS_NUTS			EQU $07

; -----------------------------
; time of day
; -----------------------------
;00-03	after midnite
;04-07	midnite
;08-0B	evening
;0C-0F	dusk
;10-13	afternoon
;14-17	noon
;18-1B	mid morning
;1C-1F	early morning

; -----------------------------
; guardians
; -----------------------------
GUARD_SAMURAI		EQU $19
GUARD_STONE_GIANT	EQU $2B
GUARD_OGRE_LORD		EQU $4A
GUARD_GREY_DRAGON	EQU $59
GUARD_GOLEM			EQU $5D