; --- Level 02 externals -------------------------------------------------
; Entry points + variables in the SHARED game code below $C18C (present in the full
; build; external to this standalone overlay). Names mirror the main build.

CHAR_NAME              EQU $0000
var_5D19               EQU $5D19
var_5D1B               EQU $5D1B
coord_ns               EQU $5FAC
facing               EQU $5FAE
var_5FCE               EQU $5FCE
var_5FD2               EQU $5FD2
var_5FD3               EQU $5FD3
treasure_flag               EQU $5FE1
view_ns               EQU $5FE3
view_we               EQU $5FE4
teleport_mode               EQU $5FE6
current_spell               EQU $5FF6
enemy_count               EQU $5FF8
var_5FFB               EQU $5FFB
var_5FFF               EQU $5FFF
clear_info_panl        EQU $6205
enter_text             EQU $6233
print_loc_name         EQU $62AA
insert_skara_tape      EQU $63BF
prep_black_color       EQU $64F3
show_some_pictext      EQU $6713
clear_txt_buffer       EQU $6734
pick_random_hero_lo               EQU $6813
combat_foes            EQU $6D4B
enter_1_to_6           EQU $7363
who_cast_spell         EQU $7539
build_creature_record               EQU $7864
spend_spell_points               EQU $794D
clean_ally_memory      EQU $7A32
apply_damage_to_group               EQU $7C4E
calc_monster_hp            EQU $85EC
teleport_to_level               EQU $876C
print_stats_table      EQU $8AEA
show_compass           EQU $8DA9
TEXT_BUFFER            EQU $FB62
DISPLAY_PALETTE        EQU $FB73
ACTIVE_GUARDIAN        EQU $FB90
COMBAT_ACTIVE_FLAG     EQU $FB98
SPELL_LIGHT_STATE      EQU $FBB4
SPELL_SECRET_STATE     EQU $FBBE
var_6004               EQU $6004
var_6006               EQU $6006
find_hero_by_B         EQU $61D9
var_6CDA               EQU $6CDA
change_speed_8         EQU $7509
add_item_to_hero               EQU $7639
var_FB90               EQU $FB90
var_FA55               EQU $FA55
call_beeper            EQU $9AA7
clear_and_print        EQU $C003
print_msg_A            EQU $C06A
overlay_end            EQU $FB50
ACTIONS_KEYS           EQU $73E8
ACTIONS_PROCS          EQU $73F2
ALLY_DATA              EQU $FD7F
ENEMY                  EQU $5CE8
GUARDIAN_TYPE          EQU $FB5C
ITEM_EFFECTS           EQU $9780
ITEM_EQUIP             EQU $9700
ITEM_SPECATT           EQU $9688
KEY_CODES_TABLE        EQU $9839
LIGHT_DURAT            EQU $94D3
MONST_HP_AC            EQU $8FCE
MONST_IMAGE            EQU $90C6
MONST_MAGIC            EQU $9182
MONST_SPEC             EQU $904E
OPTION_KEYS            EQU $8F4D
PARTY_FILE             EQU $5C68
PROCS_2                EQU $87E1
RANGE_VALUES           EQU $94C7
REVEAL_DURAT           EQU $94DF
SPELL_CARPET_STATE     EQU $FBC8
SPELL_COMPASS_STATE    EQU $FBC3
SPELL_COST             EQU $93B0
SPELL_EYE_STATE        EQU $FBD2
SPELL_REVEAL_STATE     EQU $FBB9
SPELL_SHIELD_STATE     EQU $FBCD
SPELL_TYPES            EQU $93FF
STATUSES               EQU $6176
SUMMON_CREAT           EQU $9556
WEAPON_BONUS           EQU $9611
WEAPON_DAMAGE          EQU $95BF
XP_TABLE               EQU $9146
DAYPART_ROLL_MASK             EQU $5C55
GOLD_ROLL_MASK_LO            EQU $8F24
CLASS_AC_BONUS            EQU $8F2C
PALADIN_AC_BY_LEVEL            EQU $8F36
DAYPART_DMG_SCALE            EQU $8FC6
AI_SPELL_CODES            EQU $9273
MONK_BAREHAND_DAMAGE            EQU $929A
CLASS_TO_HIT_BONUS            EQU $92B7
DAMAGE_DICE_MASK            EQU $92C1
COMBAT_SPEED_TABLE            EQU $92E2
ATTACK_WORD_TABLE            EQU $9302
DAYPART_ROLL_ADD             EQU $5C5D
ITEM_SPELL_CODES            EQU $9379
SPELL_HANDLER_PARAM            EQU $945E
___table_27            EQU $94EB
___table_28            EQU $94ED
___table_29            EQU $94EE
SWAP_STAT_TEMPLATE             EQU $7DB4
___table_30            EQU $94EF
___table_31            EQU $94F2
SPELL_AC_DELTA            EQU $94F5
SPELL_ATTACK_BONUS            EQU $94F7
DICE_SIDES_TABLE            EQU $94FA
SUMMON_DATA            EQU $9502
CLASS_ELIGIBILITY            EQU $9574
ICON_SCREEN_POS            EQU $95AD
BARD_TUNE_TABLE            EQU $97DE
SPELL_DURATIONS             EQU $82FC
___table_40            EQU $97E4
ITEM_STATE_MARKERS            EQU $97F4
CLASS_EQUIP_MASK            EQU $97F8
STAT_DISPLAY_TABLE            EQU $9802
RACE_STAT_BASE            EQU $9816
___table_46            EQU $984B
XP_CLASS_THRESHOLDS            EQU $985D
___table_48            EQU $AA7A
___table_49            EQU $AC21
SONG_EFFECT_TABLE             EQU $8308
___table_50            EQU $AE5A
___table_51            EQU $B071
___table_52            EQU $B23D
___table_53            EQU $B4F8
___table_54            EQU $B692
___table_55            EQU $B8C7
___table_56            EQU $BB03
___table_57            EQU $BCE0
SPELL_HANDLER_INDEX             EQU $881B
RND_RANGE_MASKS        EQU $8F0D
OPTION_AVAIL_MASK             EQU $8F15
GOLD_ROLL_MASK_HI             EQU $8F1C
___table_93            EQU $FD71
___table_94            EQU $FD78
___table_96            EQU $FD86
___table_97            EQU $FD8E
___table_98            EQU $FD92
___table_99            EQU $FD96
___table_9A            EQU $FD9A
___table_9B            EQU $FD9E
___table_9C            EQU $FDA2
___table_9D            EQU $FDB2
___table_9E            EQU $FDC2
___table_9F            EQU $FDC9
___table_9G            EQU $FDD0
___table_9H            EQU $FDD7
___table_9I            EQU $FF6E
___table_9J            EQU $FF75
___table_9K            EQU $FD8A
