; --- procs_buffer ---------------------------------------------
; @done
; The main RST 10h service-call dispatch table: 98 x DW handler
; addresses ($00-$61), indexed by the opcode byte that follows each
; `rst $10`. The RST 10h handler reads that byte, indexes here (index*2),
; and jumps to the routine, which then consumes any inline params. The
; trailing comment on each entry gives the opcode and its param count.
; Referenced by: RST 10h dispatcher (the *_FROM_TABLE / print macros etc.)
procs_buffer:
		DW get_attr_by_param_save_IX ; 00 (one param)
		DW show_pic_by_A				; - 01 (no param)
		DW show_pic_by_param			; - 02 (one param)
		DW show_name_pic_AB				; - 03 (no param)
		DW show_name_and_pic			; - 04 (two params)
		DW print_2newlines				; - 05 (no param)
		DW zero_buffers					; - 06 (no param)
		DW print_msg_param				; - 07 (one param)
		DW print_crlf_msg				; - 08 (one param)
		DW reset_col					; - 09 (no param)
		DW reset_row_col				; - 0A (no param)
		DW print_msg_param_2			; - 0B (one param)
		DW do_print2_in_loop			; - 0C (variable list, FF	terminated)
		DW print_in_loop				; - 0D (variable list, FF	terminated)
		DW print2_flag_0				; - 0E (no param)
		DW print2_flag_1				; - 0F (no param)
		DW print_item_name				; - 10 (no param)
		DW print_word					; - 11 (no param)
		DW clean_hero_memory			; - 12 (no param)
		DW print_IX_heroname			; - 13 (no param)
		DW print_empty					; - 14 (no param)
		DW find_hero_by_B				; - 15 (no param)
		DW find_hero_by_A				; - 16 (no param)
		DW get_attr_by_param			; - 17 (one param)
		DW get_attr_by_param_save_HL	; - 18 (one param)
		DW get_game_variable			; - 19 (one param)
		DW find_attr_and_address		; - 1A (one param)
		DW get_B_from_list				; - 1B (one param)
		DW get_C_from_list				; - 1C (one param)
		DW get_E_from_list				; - 1D (one param)
		DW prnt_with_codes				; - 1E (no param)
		DW print_digit					; - 1F (no param)
		DW prnt_next_digit				; - 20 (no param)
		DW clear_info_panl				; - 21 (no param)
		DW print_who_will				; - 22 (no param)
		DW wait_key_down				; - 23 (no param)
		DW print_and_wait				; - 24 (no param)
		DW get_rnd_numbers				; - 25 (no param)
		DW print_num_from_DE			; - 26 (no param)
		DW print_num_from_E				; - 27 (no param)
		DW check_hero_status			; - 28 (no param)
		DW change_combat_speed		; 29 (no param)
		DW check_flee_result		; 2A (no param)
		DW print_yesno_wait				; - 2B (no param)
		DW yesno_wait					; - 2C (no param)
		DW print_stats_table			; - 2D (no param)
		DW check_heroes_alive		; 2E (no param)
		DW find_alive_hero		; 2F (no param)
		DW select_combat_target		; 30 (no param)
		DW show_icon					; 31 (one param)
		DW calc_in_FB7D		; 32 (no param)
		DW change_speed					; - 33 (one param)
		DW change_speed_8				; - 34 (no param)
		DW print_space					; - 35 (no param)
		DW print_newline				; - 36 (no param)
		DW prnt_space_line				; - 37 clear 15	hor cells (no param)
		DW push_regs					; - 38 (no param)
		DW get_A_from_table				; - 39 (one param)
		DW get_B_from_table				; 3A (one param)
		DW get_C_from_table				; - 3B (one param)
		DW get_D_from_table				; 3C (one param)
		DW get_E_from_table				; 3D (one param)
		DW get_H_from_table				; 3E (one param)
		DW get_L_from_table				; 3F (one param)
		DW get_IY_A_from_table			; 40 (two params)
		DW convert_12_digits			; 41 (no param)
		DW check_spell_cost		; 42
		DW check_equipped				; 43 (one param)
		DW get_attr_by_A				; - 44 (no param)
		DW adjust_value_updown		; 45 (no param)
		DW add_rnd_number				; 46 (no param)
		DW a_plus_c_to_hl				; - 47 (no param)
		DW roll_damage_dice		; 48 (no param)
		DW reset_damage		; 49 (no param)
		DW recalc_party_ac		; 4A (no param)
		DW dispatch_movement		; 4B (no param)
		DW enter_1_to_8					; - 4C (no param)
		DW enter_1_to_6					; - 4D (no param)
		DW choose_hero					; - 4E (no param)
		DW clean_ally_memory			; - 4F (no param)
		DW find_inn						; - 50 (one param)
		DW select_random_hero		; 51 (no param)
		DW print_loc_name				; - 52 (no param)
		DW print_combat_actor		; 53 (no param)
		DW show_damage					; 54 (no param)
		DW attack_and_result			; - 55 (no param)
		DW print_memb_num				; - 56 (no param)
		DW calc_in_FD7A		; 57 (no param)
		DW clear_txt_buffer				; 58 (no param)
		DW print_letter_pair			; 59 (no param)
		DW print_hero_attr				; - 5A (no param)
		DW nullify_FB5B					; - 5B (no param)
		DW calc_monster_hp		; 5C (no param)
		DW check_three_heroes		; 5D (no param)
		DW exec_for_heroes				; - 5E (two params = address)
		DW if_FB98_is_zero	; - 5F (no param)
		DW get_rnd_by_param				; - 60 (one param)
		DW check_item_effect		; 61 (two params)
