# Generate the COMPLETE level_03 externals file by scanning every level_03 source file
# for identifiers that name a shared-engine symbol (present in the main build .sym at an
# address OUTSIDE the overlay $C18C-$FB50). This unions the handler-code externals with
# the ADDR_TABLE / decoder externals in the front matter - one EQU per symbol, no dup.
# Usage: python tools/scan_externals.py <bt.sym> <out_externals.asm> <file-or-glob> ...
import re, sys, glob

BTSYM, OUT = sys.argv[1], sys.argv[2]
OVL_LO, OVL_HI = 0xC18C, 0xFB50

ext = {}                                   # name -> addr, for shared symbols only
for line in open(BTSYM):
    m = re.match(r'(\S+):\s+EQU\s+0x0000([0-9A-Fa-f]{4})', line)
    if not m:
        continue
    a = int(m.group(2), 16)
    if a < OVL_LO or a > OVL_HI:           # outside the overlay = shared engine/vars
        ext.setdefault(m.group(1), a)

# The shared game-state vars (levels/game_vars.asm) and the ZX hardware constants
# (ZX_constants.asm) are defined in their own files, included by every level build.
# Parse their names/addresses and EXCLUDE them so we never redefine them here.
GV_NAMES, GV_ADDRS = set(), set()
for path in ("levels/game_vars.asm", "ZX_constants.asm"):
    for ln in open(path, encoding="latin-1"):
        m = re.match(r'\s*(\S+)\s+EQU\s+\$([0-9A-Fa-f]+)', ln)
        if m:
            GV_NAMES.add(m.group(1))
            GV_ADDRS.add(int(m.group(2), 16))

files = []
for pat in sys.argv[3:]:
    files += glob.glob(pat)

# labels DEFINED locally in the scanned overlays (e.g. overlay_end, MESSAGES_TABLE) -
# they must NOT be re-emitted as externals even if bt.sym also has them.
localdefs = set()
for f in files:
    for ln in open(f, encoding="latin-1"):
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*):', ln)
        if m:
            localdefs.add(m.group(1))

used = set()
varsused = {}                              # synthetic var_XXXX -> addr (from the symbolizer)
for f in files:
    for ln in open(f, encoding="latin-1"):
        code = ln.split(";", 1)[0]          # strip comment - avoid false hits in prose
        for tok in re.findall(r'[A-Za-z_][A-Za-z0-9_]*', code):
            if tok in GV_NAMES or tok in localdefs:
                continue                          # in game_vars.asm, or defined locally
            if tok in ext:
                used.add(tok)
            else:
                v = re.match(r'var_([0-9A-Fa-f]{4})$', tok)   # symbolizer's var_XXXX
                if v:
                    a = int(v.group(1), 16)
                    if (a < OVL_LO or a > OVL_HI) and a not in GV_ADDRS:
                        varsused[tok] = a

L = ["; --- Shared overlay externals (auto-generated; union across all carved levels) -----",
     "; Entry points + variables in the SHARED game code (below $C18C or above the",
     "; $FB50 overlay end), external to this standalone overlay. Names + addresses",
     "; mirror the main build .sym. Auto-generated by tools/scan_externals.py.", ""]
allsyms = {**{n: ext[n] for n in used}, **varsused}
for n in sorted(allsyms, key=lambda x: allsyms[x]):
    L.append("%-24s EQU $%04X" % (n, allsyms[n]))
open(OUT, "w", newline="\r\n").write("\n".join(L) + "\n")
print("externals: %d (%d named + %d var_)" % (len(allsyms), len(used), len(varsused)))
