PROCS_3:
		dw proc_emptybuild
		dw proc_guild
		dw proc_tavern
		dw proc_shoppe
		dw proc_temple
		dw proc_reviewbord
		dw 0
		dw proc_emptybuild
		dw 0
		dw 0
		dw 0
		dw 0
		dw proc_guardian
		dw proc_iron_gate
		dw proc_mad_god
		dw proc_city_sewers
		dw proc_emptybuild
		dw proc_roscoe
		dw proc_amber
		dw proc_castle
		dw proc_mangar_saved
		dw proc_gate_closed
